experimentalTernaries: true
# printWidth: 80
tabWidth: 4
useTabs: true
singleQuote: true
jsxSingleQuote: true
trailingComma: 'es5'
bracketSpacing: true
# bracketSameLine: true
plugins: ['prettier-plugin-tailwindcss']
